
# ~/.config/sheldon/plugins.toml

shell = "zsh"

# 1. fzf-tab
[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"

[plugins.zoxide]
inline = 'eval "$(zoxide init zsh)"'

# 2. 语法高亮 (建议放在最后加载)
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
